name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package (test extras)
        run: pip install -e .[test]

      - name: Run unit tests
        run: pytest -q

  pg-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: expressiondb
          POSTGRES_USER: expressiondb
          POSTGRES_PASSWORD: supersecret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U expressiondb -d expressiondb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package (test + pg extras)
        run: pip install -e .[test,pg]

      - name: Run DB tests
        run: pytest -q
        env:
          DATABASE_URL: postgresql://expressiondb:supersecret@localhost:5432/expressiondb
